petr_subotnik/week05/tuesday/beerking/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "beer_countries#index"
  resources :beer_countries
  resources :beer_brands
end

petr_subotnik/week05/tuesday/beerking/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

petr_subotnik/week05/tuesday/beerking/app/models/beer_brand.rb
class BeerBrand < ApplicationRecord
  belongs_to :beer_country
end

petr_subotnik/week05/tuesday/beerking/app/models/beer_country.rb
class BeerCountry < ApplicationRecord
  has_many :beer_brands
end

petr_subotnik/week05/tuesday/beerking/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

petr_subotnik/week05/tuesday/beerking/app/controllers/beer_brands_controller.rb
class BeerBrandsController < ApplicationController
  def new
    @beer_brand = BeerBrand.new
    @beer_country_id = params[:beer_country_id]
  end

  def create
    @beer_brand = BeerBrand.new(clean_params)
    if @beer_brand.save
      redirect_to beer_country_path(@beer_brand.beer_country_id)
    else
      render :new
    end
  end

  private

  def clean_params
    params.require(:beer_brand).permit(:name, :image_src, :beer_country_id)
  end
end

petr_subotnik/week05/tuesday/beerking/app/controllers/beer_countries_controller.rb
class BeerCountriesController < ApplicationController
def index
    @beer_countries = BeerCountry.all
  end

  def new
    @beer_country = BeerCountry.new
  end

  def create
    @beer_country = BeerCountry.new(clean_params)
    if @beer_country.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @beer_country = BeerCountry.find(params[:id])
  end

  def destroy
    @beer_country = BeerCountry.find(params[:id]).destroy
    redirect_to root_path
  end

  private

  def clean_params
    params.require(:beer_country).permit(:name, :image_src)
  end
end

petr_subotnik/week05/tuesday/beerking/app/helpers/application_helper.rb
module ApplicationHelper
end

petr_subotnik/week05/tuesday/beerking/app/views/beer_countries/index.html.erb
<h1>Beer Countries</h1>
<%= link_to "New Beer Country", new_beer_country_path %>
<ul>
  <% @beer_countries.each do |bc| %>
    <li><%= link_to bc.name, beer_country_path(bc.id) %> | <%= link_to "Delete", beer_country_path(bc.id), method: :delete%></li>
  <%end%>
 </ul>
  

petr_subotnik/week05/tuesday/beerking/app/views/beer_countries/new.html.erb
<% if @beer_country.errors %>
  <ul>
    <% @beer_country.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <%end%>
  </ul>
<%end%>

<%= form_for @beer_country do |b|%>
  <p>
    <%= b.label :name %>
    <%= b.text_field :name %>
  </p>
  <p>
    <%= b.label :image_src %>
    <%= b.text_field :image_src %>
  </p>
  <%= b.submit %>
<%end%>

petr_subotnik/week05/tuesday/beerking/app/views/beer_countries/show.html.erb
<h1><%= @beer_country.name %></h1>
<%= link_to "New Beer Brand", new_beer_brand_path(beer_country_id: @beer_country.id) %>
<ul>
  <% @beer_country.beer_brands.each do |bb| %>
    <li><%= bb.name %></li>
  <%end%>
</ul>