henrietta_chow/week05/trangr/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "countries#index"
  get "/countries", to: "countries#show", as: "country"
  delete "/countries", to: "countries#destroy"
  get "/landmarks", to: "landmarks#select", as: "landmark_select"

  resources :countries, only: [:new, :edit, :update, :create]
  resources :cities, only: [:show, :create, :new, :destroy]
  resources :activities, only: [:show, :create, :new]
  resources :landmarks, only: [:create, :new, :destroy]

  get "signup", to: "users#new", as: "signup"
  resources :users, only: [:create]

  get "signin", to: "sessions#new", as: "signin"
  post "signin", to: "sessions#create"
  delete "signout", to: "sessions#destroy", as:"signout"
end

henrietta_chow/week05/trangr/app/models/activities_city.rb
class ActivitiesCity < ActiveRecord::Base
  validates_uniqueness_of :activity_id, scope: :city_id
end

henrietta_chow/week05/trangr/app/models/activity.rb
class Activity < ApplicationRecord
  has_and_belongs_to_many :cities, -> { distinct }
  validates_uniqueness_of :name
end

henrietta_chow/week05/trangr/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

henrietta_chow/week05/trangr/app/models/city.rb
class City < ApplicationRecord
  belongs_to :country
  has_many :landmarks, dependent: :destroy
  has_and_belongs_to_many :activities, -> { distinct }
  validates_uniqueness_of :name
end

henrietta_chow/week05/trangr/app/models/country.rb
class Country < ApplicationRecord
  has_many :cities, dependent: :destroy
  has_many :landmarks, through: :cities
  validates_uniqueness_of :name
end

henrietta_chow/week05/trangr/app/models/landmark.rb
class Landmark < ApplicationRecord
  belongs_to :city
end

henrietta_chow/week05/trangr/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_uniqueness_of :email
  validates :email, exclusion: {
    in: ["xander@me.com", "xander@ga.com"],
    message "This is a forbidden email"
  }
  validates :email, format: {
    with: /\A.*@wdi.com\z/
  }
end

henrietta_chow/week05/trangr/app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user, only: [:create]

  def show
    @activity = Activity.find(params[:id])
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.find_or_create_by(name: params[:activity][:name])
    @city = City.find(params[:city_id])
    @city.activities << @activity

    if @activity.save
      redirect_to city_path(params[:city_id])
    else
      render :new
    end
  end

  private

  def clean_params
    params.require(:activity).require(:name)
  end

end

henrietta_chow/week05/trangr/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :fetch_user

  private

  def fetch_user
    @current_user = User.find_by_id(session[:user_id])
  end

  def authenticate_user
    if @current_user.nil?
      flash[:error] = "Access Denied"
      return redirect_to root_path
    end
  end

end

henrietta_chow/week05/trangr/app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :authenticate_user, only: [:create, :destroy]

  def show
    @city = City.find(params[:id])
  end

  def create
    @city = City.create(clean_params)
    if @city.save
      redirect_to city_path(@city.id)
    else
      render :new
    end
  end

  def new
    @city = City.new
  end

  def destroy
    city = City.find(params[:city_id]).destroy
    redirect_to controller: "countries", action: "show", country_id: city.country_id
  end

  private

  def clean_params
    params.require(:city).permit(:name, :country_id)
  end

end

henrietta_chow/week05/trangr/app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :authenticate_user, only: [:create, :edit, :update, :destroy]

  def index
    @countries = Country.all
  end

  def show
    flash[:success] = "We found the country for you :)"
    @country = Country.find(params[:country_id])
  end

  def create
    @country = Country.create(clean_params)
    if @country.save
      redirect_to controller: "countries", action: "show", country_id: @country.id
    else
      render :new
    end
  end

  def new
    @country = Country.new
  end

  def edit
    @country = Country.find(params[:id])
  end

  def update
    @country = Country.find(params[:id])
    if @country.update_attributes(clean_params)
      redirect_to controller: "countries", action: "show", id: params[:id]
    else
      render :edit
    end
  end

  def destroy
    if @current_user.admin
      country = Country.find(params[:id]).destroy
      flash[:success] = "You deleted #{country.name}."
      redirect_to root_path
    else
      flash[:error] = "Action denied"
      redirect_to root_path
   end

  private

  def clean_params
    params.require(:country).permit(:name)
  end

end

henrietta_chow/week05/trangr/app/controllers/landmarks_controller.rb
class LandmarksController < ApplicationController
  before_action :authenticate_user, only: [:create, :destroy]

  def new
    @landmark = Landmark.new
  end

  def create
    @landmark = Landmark.create(clean_params)

    if @landmark.save
      redirect_to city_path(@landmark.city_id)
    else
      render :new
    end
  end

  def select
    @landmarks = City.find(params[:city_id]).landmarks
  end

  def destroy
    landmark = Landmark.find(params[:landmark_id]).destroy
    redirect_to city_path(landmark.city_id)
  end

  private

  def clean_params
    params.require(:landmark).permit(:name, :image, :city_id)
  end

end

henrietta_chow/week05/trangr/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user
      if user.authenticate(params[:password])
        # we have a real user
        session[:user_id] = user.id
        redirect_to root_path
      else
        render :new
      end
    else
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

henrietta_chow/week05/trangr/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user

  def new
    @user = User.new
  end

  def create
    @user = User.new(clean_params)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def clean_params
    params.require(:user).permit(:email, :password)
  end

end

henrietta_chow/week05/trangr/app/helpers/application_helper.rb
module ApplicationHelper
  
end

henrietta_chow/week05/trangr/app/views/cities/new.html.erb
<% if @city.errors %>
  <ul>
    <% @city.errors.full_messages.each do |msg| %>
      <li><<%= msg %></li>
    <% end %>
  </ul>
<% end %>


<h1>Been Somewhere Exciting?</h1>
<%= form_for @city do |c| %>
  <input type="hidden" name="city[country_id]" value="<%= params[:country_id] %>"/>
  <p>
    <%= c.label "Name" %>
    <%= c.text_field :name %>
  </p>
  <p>
    <%= c.submit class: "ui primary button"%>
<% end %>

henrietta_chow/week05/trangr/app/views/cities/show.html.erb
<h1>This is <%= @city.name %>!</h1>
<% if @current_user %>
  <%= link_to "Delete City", city_path(city_id: @city.id), method: :delete %> |
  <%= link_to "Add an Activity", new_activity_path(city_id: @city.id) %> |
  <%= link_to "Add a Landmark", new_landmark_path(city_id: @city.id) %> |
  <%= link_to "Delete a Landmark", landmark_select_path(city_id: @city.id) %>
<% end %>

<h3>Activities</h3>
<ul>
  <% @city.activities.each do |a| %>
    <li><%= link_to a.name, activity_path(a.id) %></li>
  <% end %>
</ul>

<h3>Landmarks</h3>
<ul>
  <% @city.landmarks.each do |l| %>
    <li><%= l.name %></li>
  <% end %>
</ul>

henrietta_chow/week05/trangr/app/views/includes/_flash_notices.html.erb
<% if flash %>
  <% flash.each do |k,v| %>
    <div class="ui message transition <%= k.to_s %>">
      <i class="close icon"></i>
      <div class="header">
        <%= k.to_s.capitalize %>
      </div>
      <p><%= v %></p>
    </div>
  <%end%>
  <% flash.clear %>
<%end%>

henrietta_chow/week05/trangr/app/views/includes/_footer.html.erb
<div class="ui inverted vertical footer segment">
  <div class="ui center aligned container">
    <div class="ui stackable inverted divided grid">
      <div class="three wide column">
        <h4 class="ui inverted header">Group 1</h4>
        <div class="ui inverted link list">
          <a href="#" class="item">Link One</a>
          <a href="#" class="item">Link Two</a>
          <a href="#" class="item">Link Three</a>
          <a href="#" class="item">Link Four</a>
        </div>
      </div>
      <div class="three wide column">
        <h4 class="ui inverted header">Group 2</h4>
        <div class="ui inverted link list">
          <a href="#" class="item">Link One</a>
          <a href="#" class="item">Link Two</a>
          <a href="#" class="item">Link Three</a>
          <a href="#" class="item">Link Four</a>
        </div>
      </div>
      <div class="three wide column">
        <h4 class="ui inverted header">Group 3</h4>
        <div class="ui inverted link list">
          <a href="#" class="item">Link One</a>
          <a href="#" class="item">Link Two</a>
          <a href="#" class="item">Link Three</a>
          <a href="#" class="item">Link Four</a>
        </div>
      </div>
      <div class="seven wide column">
        <h4 class="ui inverted header">Footer Header</h4>
        <p>Extra space for a call to action inside the footer that could help re-engage users.</p>
      </div>
    </div>
    <div class="ui inverted section divider"></div>
    <div class="ui horizontal inverted small divided link list">
      <a class="item" href="#">Site Map</a>
      <a class="item" href="#">Contact Us</a>
      <a class="item" href="#">Terms and Conditions</a>
      <a class="item" href="#">Privacy Policy</a>
    </div>
  </div>
</div>

henrietta_chow/week05/trangr/app/views/includes/_navigation.html.erb
<div class="ui fixed inverted menu">
  <div class="ui container">
    <%= link_to root_path, class: "header item" do %>
      <%= image_tag "logo.png", class: "logo" %>
      Trangr
    <%end%>
    <%= link_to "Home", root_path, class: "item" %>
    <%= link_to "Sign In", signin_path, class: "item" %>
    <%= link_to "Sign Out", signout_path, class: "item", method: :delete %>
    <% if @current_user %>
      <%= link_to "New Admin", signup_path, class: "item" %>
      <%= link_to "Add a Country", new_country_path, method: :get, class: "item" %>
    <% end %>
  </div>
</div>

henrietta_chow/week05/trangr/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trangr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "includes/navigation" %>

    <div class="ui main text container">
      <%= render "includes/flash_notices" %>
      <%= yield %>
    </div>
    <%= render "includes/footer" %>
  </body>
</html>

henrietta_chow/week05/trangr/app/views/users/new.html.erb
<% if @user.errors %>
  <ul>
    <% @user.errors.full_messages.each do |m| %>
      <li><%= m  %></li>
    <% end %>
<% end %>
<%= form_for @user do |f| %>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
    <%= f.submit "Sign up", class: "ui primary button" %>
<% end %>